## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,2,94,3,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,3,61,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,92,2,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,4,56,3,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,Research & Development,2,1,Medical,1,40,3,...,3,4,1,6,3,3,2,2,2,2

In [2]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
y_df.head()

  Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [4]:
attrition_df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [5]:
# Create a list of at least 10 column names to use as X data
list = ['Age', 'BusinessTravel', 'DistanceFromHome',
       'Education', 'EducationField', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating']

# Create X_df using your selected columns
X_df = attrition_df[list]

# Show the data types for X_df
X_df.dtypes

Age                         int64
BusinessTravel             object
DistanceFromHome            int64
Education                   int64
EducationField             object
EnvironmentSatisfaction     int64
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                    object
JobSatisfaction             int64
MaritalStatus              object
NumCompaniesWorked          int64
OverTime                   object
PercentSalaryHike           int64
PerformanceRating           int64
dtype: object

In [28]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=1)

In [9]:
# Convert your X data to numeric data types however you see fit
from sklearn.preprocessing import OneHotEncoder
# Encode categorical data with OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)
# Define columns to encode
columns_to_encode = ['BusinessTravel', 'EducationField', 'JobRole', 'MaritalStatus', 'OverTime']
# Fit and transform
encoded_train = ohe.fit_transform(X_train[columns_to_encode])
# Create a new DataFrame with the encoded data
encoded_df = pd.DataFrame(encoded_train, columns=ohe.get_feature_names_out(columns_to_encode))
# Combine with original dataframe
X_train = pd.concat([X_train.drop(columns=columns_to_encode), encoded_df], axis=1)
# Transform the testing data using the same encoder
encoded_test = ohe.transform(X_test[columns_to_encode])
encoded_df_test = pd.DataFrame(encoded_test, columns=ohe.get_feature_names_out(columns_to_encode))
X_test = pd.concat([X_test.drop(columns=columns_to_encode), encoded_df_test], axis=1)
X_train.head()

,Age,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,NumCompaniesWorked,PercentSalaryHike,...,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,OverTime_No,OverTime_Yes
464,37.0,1.0,3.0,2.0,59.0,3.0,3.0,4.0,4.0,17.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
512,27.0,3.0,4.0,1.0,54.0,2.0,1.0,4.0,0.0,13.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
480,30.0,12.0,4.0,2.0,74.0,2.0,1.0,1.0,1.0,18.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
680,36.0,7.0,4.0,2.0,65.0,3.0,1.0,4.0,2.0,18.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1023,56.0,1.0,2.0,1.0,90.0,3.0,1.0,1.0,2.0,22.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [19]:
# Create a StandardScaler
ss = StandardScaler()

# Fit the StandardScaler to the training data
ss.fit(X_train)

# Scale the training and testing data
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

In [20]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
ohe = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
ohe.fit(y_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
encoded_train2 = ohe.fit_transform(y_train[['Department']])
encoded_test2 = ohe.transform(y_test[['Department']])

In [21]:
# Create a OneHotEncoder for the Attrition column
ohe = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
ohe.fit(y_train[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data
encoded_train3 = ohe.fit_transform(y_train[['Attrition']])
encoded_test3 = ohe.transform(y_test[['Attrition']])

## Part 2: Create, Compile, and Train the Model

In [13]:
# Find the number of columns in the X training data.
X_train_scaled.shape

# Create the input layer
input_layer = layers.Input(shape=(X_train_scaled.shape[1],))

# Create at least two shared layers
shared_layer1 = layers.Dense(units=64, activation='relu')(input_layer)
shared_layer2 = layers.Dense(units=32, activation='relu')(shared_layer1)

In [15]:
# Create a branch for Department
# with a hidden layer and an output layer
department_branch = layers.Dense(units=32, activation='relu')(shared_layer2)

# Create the hidden layer
hidden_layer = layers.Dense(units=64, activation='relu')(shared_layer2)

# Create the output layer
output_layer = layers.Dense(units=3, activation='softmax')(department_branch)

In [16]:
# Create a branch for Attrition
# with a hidden layer and an output layer
attrition_branch = layers.Dense(units=32, activation='relu')(shared_layer2)
# Create the hidden layer
hidden_layer = layers.Dense(units=64, activation='relu')(shared_layer2)

# Create the output layer
output_layer = layers.Dense(units=2, activation='softmax')(attrition_branch)

In [42]:
# Create the model
model = Model(inputs=input_layer, outputs=[output_layer, attrition_branch])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Summarize the model
model.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (None, 34)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 64)                  │           2,240 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 32)                  │           1,056 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 2)                   │              66 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,442 (21.26 KB)

 Trainable params: 5,442 (21.26 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Train the model
X_train_scaled = X_train_scaled[:len(encoded_train2)]
batch_size = 32
epochs = 10

# Change the loss function to a dictionary to specify loss for each output
history = model.fit(
    X_train_scaled,
    {"department_branch": encoded_train2, "attrition_branch": encoded_train3},
    batch_size=batch_size,
    epochs=epochs
)

In [ ]:
# Evaluate the model with the testing data
eval_results = model.evaluate(X_test_scaled, [encoded_test2, encoded_test3])

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.7868 - department_output_accuracy: 0.4877 - loss: 4.0711

[4.038690090179443, 0.7880434989929199, 0.5]

In [ ]:
# Print the accuracy for both department and attrition
print(f"Department Accuracy: {eval_results[2]}")
print(f"Attrition Accuracy: {eval_results[3]}")

Attrition predictions accuracy: 0.7880434989929199
Department predictions accuracy: 0.5

# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Accuracy might not be the most reliable metric when dealing with an imbalanced dataset, where one class has a much larger number of samples than the other. In these situations, accuracy can give a falsely high value, even if the model struggles with predicting the minority class effectively.
2. Softmax is employed in the output layers of both the department and attrition branches because it generates a probability distribution across multiple classes. This makes it ideal for multi-class classification tasks, like predicting the department (with 3 classes) or attrition (with 2 classes).
3. Try different hyperparameters, such as the number of layers, neurons in each layer, activation functions, and optimizers, by using methods like grid search or random search.